services:
  postgres:
    container_name: core-postgres
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: outbox_user
      POSTGRES_PASSWORD: outbox_password
      POSTGRES_DB: core_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U outbox_user -d core_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - outbox-network

  order-service:
    build:
      context: .
      dockerfile: services/order/Dockerfile
    environment:
      DATABASE_URL: postgresql://outbox_user:outbox_password@postgres:5432/core_db
    ports:
      - "3123:3123"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - outbox-network

  relay-service:
    build:
      context: ./services/relay
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://outbox_user:outbox_password@postgres:5432/core_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - outbox-network

#   rabbitmq:
#     image: rabbitmq:3-management
#     ports:
#       - 5672:5672
#       - 15672:15672
#   email-service:
    
  
volumes:
  postgres_data:
  node_modules:

networks:
  outbox-network:
    driver: bridge

  