services:
  postgres:
    container_name: core-postgres
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: outbox_user
      POSTGRES_PASSWORD: outbox_password
      POSTGRES_DB: core_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U outbox_user -d core_db"]
      interval: 5s
      timeout: 5s
      retries: 5

#   order-service:
#     build:
#       context: ./services/order
#       dockerfile: Dockerfile
#     environment:
#       NODE_ENV: development
#       DATABASE_URL: postgresql://outbox_user:outbox_password@postgres:5432/outbox_db
#     ports:
#       - "3000:3000"
#     depends_on:
#       postgres:
#         condition: service_healthy
#     volumes:
#       - ./services/order-service:/app
#       - /app/node_modules

#   relay-service:
#     build:
#       context: ./services/relay
#       dockerfile: Dockerfile
#     environment:
#       NODE_ENV: development
#       DATABASE_URL: postgresql://outbox_user:outbox_password@postgres:5432/outbox_db
#     depends_on:
#       postgres:
#         condition: service_healthy
#     volumes:
#       - ./services/relay-service:/app
#       - /app/node_modules

#   rabbitmq:
#     image: rabbitmq:3-management
#     ports:
#       - 5672:5672
#       - 15672:15672
#   email-service:
    
  
volumes:
  postgres_data:

networks:
  default:
    name: outbox-network

  